### ISSUE TITLE
File Drive install on osTicket 1.15.2

### ISSUE THREAD

**Issue by kfn8dkodemonkey** [akshaynikhare/FileDrive#1]
Installing FileDrive on osTicket 1.15.2

I have extracted the files to my desktop I see there is a directory in the FileDrive-Master directory called  _copy_to _root. Am I to copy the contents of this folder to the FileDrive folder?

Also not sure what you mean by "fd-config need to be configured".

I am able to (though many assumed variations) almost have it installed. However, once I enable it then go to another page ti get this error: "Get technical help from plugin Supplier " FileDrive " "

any help installing would be great.
Heather The Kodemonkey

**Comment by akshaynikhare** [comment]
@kfn8dkodemonkey  just rename the plugin folder to "FileDrive" and Copy/Paste in the Osticket Root > include > plugin  
nothing else is needed.

![image](https://user-images.githubusercontent.com/9725336/113516028-af617e80-9595-11eb-807f-d60e3e0dc21f.png)
